#ifndef BCC_PARSER_BMX_RELEASE_HAIKU_X64_H
#define BCC_PARSER_BMX_RELEASE_HAIKU_X64_H

#include <brl.mod/blitz.mod/.bmx/blitz.bmx.release.haiku.x64.h>
#include <brl.mod/standardio.mod/.bmx/standardio.bmx.release.haiku.x64.h>
#include <brl.mod/maxutil.mod/.bmx/maxutil.bmx.release.haiku.x64.h>
#include "toker.bmx.release.haiku.x64.h"
int _bb_bcc_parser();
struct _m_parser_TIParser_obj;
struct _m_parser_TForEachinStmt_obj;
struct _m_parser_TIncbin_obj;
struct _m_parser_TParser_obj;
struct _m_parser_TCastDets_obj;
extern BBSTRING _m_parser_FILE_EXT;
void __m_parser_TIParser_New(struct _m_parser_TIParser_obj* o);
typedef BBINT (*_m_parser_TIParser_ParseModuleImport_TTModuleDeclSSSSiSi_m)(struct _m_parser_TIParser_obj*,struct _m_type_TModuleDecl_obj*,BBSTRING,BBSTRING,BBSTRING,BBSTRING,BBINT,BBSTRING,BBINT);
BBINT __m_parser_TIParser_ParseModuleImport_TTModuleDeclSSSSiSi(struct _m_parser_TIParser_obj*,struct _m_type_TModuleDecl_obj*,BBSTRING,BBSTRING,BBSTRING,BBSTRING,BBINT,BBSTRING,BBINT);
typedef struct _m_type_TExpr_obj* (*_m_parser_TIParser_ParseUnaryExpr_m)(struct _m_parser_TIParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TIParser_ParseUnaryExpr(struct _m_parser_TIParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TIParser_ParsePrimaryExpr_i_m)(struct _m_parser_TIParser_obj*,BBINT);
struct _m_type_TExpr_obj* __m_parser_TIParser_ParsePrimaryExpr_i(struct _m_parser_TIParser_obj*,BBINT);
typedef struct _m_type_TClassDecl_obj* (*_m_parser_TIParser_ParseClassDecl_Si_m)(struct _m_parser_TIParser_obj*,BBSTRING,BBINT);
struct _m_type_TClassDecl_obj* __m_parser_TIParser_ParseClassDecl_Si(struct _m_parser_TIParser_obj*,BBSTRING,BBINT);
typedef struct _m_type_TEnumDecl_obj* (*_m_parser_TIParser_ParseEnumDecl_S_m)(struct _m_parser_TIParser_obj*,BBSTRING);
struct _m_type_TEnumDecl_obj* __m_parser_TIParser_ParseEnumDecl_S(struct _m_parser_TIParser_obj*,BBSTRING);
typedef struct _m_type_TEnumValueDecl_obj* (*_m_parser_TIParser_ParseEnumValueDecl_SiTTType_m)(struct _m_parser_TIParser_obj*,BBSTRING,BBINT,struct _m_type_TType_obj*);
struct _m_type_TEnumValueDecl_obj* __m_parser_TIParser_ParseEnumValueDecl_SiTTType(struct _m_parser_TIParser_obj*,BBSTRING,BBINT,struct _m_type_TType_obj*);
typedef void (*_m_parser_TIParser_Parse_S_m)(struct _m_parser_TIParser_obj*,BBSTRING);
void __m_parser_TIParser_Parse_S(struct _m_parser_TIParser_obj*,BBSTRING);
typedef BBSTRING (*_m_parser_TIParser_ParseIdent_m)(struct _m_parser_TIParser_obj*);
BBSTRING __m_parser_TIParser_ParseIdent(struct _m_parser_TIParser_obj*);
typedef struct _m_type_TIdentType_obj* (*_m_parser_TIParser_ParseIdentType_m)(struct _m_parser_TIParser_obj*);
struct _m_type_TIdentType_obj* __m_parser_TIParser_ParseIdentType(struct _m_parser_TIParser_obj*);
typedef BBSTRING (*_m_parser_TIParser_NextToke_m)(struct _m_parser_TIParser_obj*);
BBSTRING __m_parser_TIParser_NextToke(struct _m_parser_TIParser_obj*);
typedef BBINT (*_m_parser_TIParser_CParse_S_m)(struct _m_parser_TIParser_obj*,BBSTRING);
BBINT __m_parser_TIParser_CParse_S(struct _m_parser_TIParser_obj*,BBSTRING);
typedef BBINT (*_m_parser_TIParser_CParseToker_TTTokerS_m)(struct _m_parser_TIParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
BBINT __m_parser_TIParser_CParseToker_TTTokerS(struct _m_parser_TIParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
typedef BBSTRING (*_m_parser_TIParser_NextTokeToker_TTToker_m)(struct _m_parser_TIParser_obj*,struct _m_toker_TToker_obj*);
BBSTRING __m_parser_TIParser_NextTokeToker_TTToker(struct _m_parser_TIParser_obj*,struct _m_toker_TToker_obj*);
typedef void (*_m_parser_TIParser_SkipEols_m)(struct _m_parser_TIParser_obj*);
void __m_parser_TIParser_SkipEols(struct _m_parser_TIParser_obj*);
typedef BBSTRING (*_m_parser_TIParser_ParseStringLit_m)(struct _m_parser_TIParser_obj*);
BBSTRING __m_parser_TIParser_ParseStringLit(struct _m_parser_TIParser_obj*);
typedef struct _m_type_TFuncDecl_obj* (*_m_parser_TIParser_ParseFuncDecl_SiTTTypeTTClassDecl_m)(struct _m_parser_TIParser_obj*,BBSTRING,BBINT,struct _m_type_TType_obj*,struct _m_type_TClassDecl_obj*);
struct _m_type_TFuncDecl_obj* __m_parser_TIParser_ParseFuncDecl_SiTTTypeTTClassDecl(struct _m_parser_TIParser_obj*,BBSTRING,BBINT,struct _m_type_TType_obj*,struct _m_type_TClassDecl_obj*);
typedef struct _m_type_TDecl_obj* (*_m_parser_TIParser_ParseDecl_Si_m)(struct _m_parser_TIParser_obj*,BBSTRING,BBINT);
struct _m_type_TDecl_obj* __m_parser_TIParser_ParseDecl_Si(struct _m_parser_TIParser_obj*,BBSTRING,BBINT);
typedef struct _m_type_TType_obj* (*_m_parser_TIParser_ParseArrayType_TTTypei_m)(struct _m_parser_TIParser_obj*,struct _m_type_TType_obj*,BBINT);
struct _m_type_TType_obj* __m_parser_TIParser_ParseArrayType_TTTypei(struct _m_parser_TIParser_obj*,struct _m_type_TType_obj*,BBINT);
typedef BBINT (*_m_parser_TIParser_IstStaticArrayDef_m)(struct _m_parser_TIParser_obj*);
BBINT __m_parser_TIParser_IstStaticArrayDef(struct _m_parser_TIParser_obj*);
typedef BBINT (*_m_parser_TIParser_IsArrayDef_i_m)(struct _m_parser_TIParser_obj*,BBINT);
BBINT __m_parser_TIParser_IsArrayDef_i(struct _m_parser_TIParser_obj*,BBINT);
typedef struct _m_type_TType_obj* (*_m_parser_TIParser_ParseDeclType_vii_m)(struct _m_parser_TIParser_obj*,BBINT*,BBINT);
struct _m_type_TType_obj* __m_parser_TIParser_ParseDeclType_vii(struct _m_parser_TIParser_obj*,BBINT*,BBINT);
typedef struct _m_type_TType_obj* (*_m_parser_TIParser_ParseNewType_m)(struct _m_parser_TIParser_obj*);
struct _m_type_TType_obj* __m_parser_TIParser_ParseNewType(struct _m_parser_TIParser_obj*);
typedef void (*_m_parser_TIParser_ApplyFunctionAttributes_TTClassDecli_m)(struct _m_parser_TIParser_obj*,struct _m_type_TClassDecl_obj*,BBINT);
void __m_parser_TIParser_ApplyFunctionAttributes_TTClassDecli(struct _m_parser_TIParser_obj*,struct _m_type_TClassDecl_obj*,BBINT);
typedef void (*_m_parser_TIParser_SetErr_m)(struct _m_parser_TIParser_obj*);
void __m_parser_TIParser_SetErr(struct _m_parser_TIParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TIParser_ParseType_m)(struct _m_parser_TIParser_obj*);
struct _m_type_TType_obj* __m_parser_TIParser_ParseType(struct _m_parser_TIParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TIParser_CParsePrimitiveType_m)(struct _m_parser_TIParser_obj*);
struct _m_type_TType_obj* __m_parser_TIParser_CParsePrimitiveType(struct _m_parser_TIParser_obj*);
struct BBClass__m_parser_TIParser {
	BBClass*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	_m_parser_TIParser_ParseModuleImport_TTModuleDeclSSSSiSi_m m_ParseModuleImport_TTModuleDeclSSSSiSi;
	_m_parser_TIParser_ParseUnaryExpr_m m_ParseUnaryExpr;
	_m_parser_TIParser_ParsePrimaryExpr_i_m m_ParsePrimaryExpr_i;
	_m_parser_TIParser_ParseClassDecl_Si_m m_ParseClassDecl_Si;
	_m_parser_TIParser_ParseEnumDecl_S_m m_ParseEnumDecl_S;
	_m_parser_TIParser_ParseEnumValueDecl_SiTTType_m m_ParseEnumValueDecl_SiTTType;
	_m_parser_TIParser_Parse_S_m m_Parse_S;
	_m_parser_TIParser_ParseIdent_m m_ParseIdent;
	_m_parser_TIParser_ParseIdentType_m m_ParseIdentType;
	_m_parser_TIParser_NextToke_m m_NextToke;
	_m_parser_TIParser_CParse_S_m m_CParse_S;
	_m_parser_TIParser_CParseToker_TTTokerS_m m_CParseToker_TTTokerS;
	_m_parser_TIParser_NextTokeToker_TTToker_m m_NextTokeToker_TTToker;
	_m_parser_TIParser_SkipEols_m m_SkipEols;
	_m_parser_TIParser_ParseStringLit_m m_ParseStringLit;
	_m_parser_TIParser_ParseFuncDecl_SiTTTypeTTClassDecl_m m_ParseFuncDecl_SiTTTypeTTClassDecl;
	_m_parser_TIParser_ParseDecl_Si_m m_ParseDecl_Si;
	_m_parser_TIParser_ParseArrayType_TTTypei_m m_ParseArrayType_TTTypei;
	_m_parser_TIParser_IstStaticArrayDef_m m_IstStaticArrayDef;
	_m_parser_TIParser_IsArrayDef_i_m m_IsArrayDef_i;
	_m_parser_TIParser_ParseDeclType_vii_m m_ParseDeclType_vii;
	_m_parser_TIParser_ParseNewType_m m_ParseNewType;
	_m_parser_TIParser_ApplyFunctionAttributes_TTClassDecli_m m_ApplyFunctionAttributes_TTClassDecli;
	_m_parser_TIParser_SetErr_m m_SetErr;
	_m_parser_TIParser_ParseType_m m_ParseType;
	_m_parser_TIParser_CParsePrimitiveType_m m_CParsePrimitiveType;
};

struct _m_parser_TIParser_obj {
	struct BBClass__m_parser_TIParser* clas;
	struct _m_toker_TToker_obj* __m_parser_tiparser__toker;
	BBSTRING __m_parser_tiparser__toke;
	BBINT __m_parser_tiparser__toketype;
	BBINT __m_parser_tiparser__tokespace;
	struct brl_linkedlist_TList_obj* __m_parser_tiparser__tokerstack;
};
extern struct BBClass__m_parser_TIParser _m_parser_TIParser;
void __m_parser_TForEachinStmt_New(struct _m_parser_TForEachinStmt_obj* o);
typedef struct _m_parser_TForEachinStmt_obj* (*_m_parser_TForEachinStmt_Create_STTTypeiTTExprTTBlockDeclTTLoopLabelDeclTTExpr_m)(struct _m_parser_TForEachinStmt_obj*,BBSTRING,struct _m_type_TType_obj*,BBINT,struct _m_type_TExpr_obj*,struct _m_type_TBlockDecl_obj*,struct _m_type_TLoopLabelDecl_obj*,struct _m_type_TExpr_obj*);
struct _m_parser_TForEachinStmt_obj* __m_parser_TForEachinStmt_Create_STTTypeiTTExprTTBlockDeclTTLoopLabelDeclTTExpr(struct _m_parser_TForEachinStmt_obj*,BBSTRING,struct _m_type_TType_obj*,BBINT,struct _m_type_TExpr_obj*,struct _m_type_TBlockDecl_obj*,struct _m_type_TLoopLabelDecl_obj*,struct _m_type_TExpr_obj*);
typedef struct _m_type_TStmt_obj* (*_m_parser_TForEachinStmt_OnCopy_TTScopeDecl_m)(struct _m_parser_TForEachinStmt_obj*,struct _m_type_TScopeDecl_obj*);
struct _m_type_TStmt_obj* __m_parser_TForEachinStmt_OnCopy_TTScopeDecl(struct _m_parser_TForEachinStmt_obj*,struct _m_type_TScopeDecl_obj*);
typedef void (*_m_parser_TForEachinStmt_OnSemant_m)(struct _m_parser_TForEachinStmt_obj*);
void __m_parser_TForEachinStmt_OnSemant(struct _m_parser_TForEachinStmt_obj*);
typedef BBSTRING (*_m_parser_TForEachinStmt_Trans_m)(struct _m_parser_TForEachinStmt_obj*);
BBSTRING __m_parser_TForEachinStmt_Trans(struct _m_parser_TForEachinStmt_obj*);
struct BBClass__m_parser_TForEachinStmt {
	struct BBClass__m_type_TLoopStmt*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	_m_parser_TForEachinStmt_OnCopy_TTScopeDecl_m m_OnCopy_TTScopeDecl;
	_m_type_TStmt_Semant_m m_Semant;
	_m_type_TStmt_Copy_TTScopeDecl_m m_Copy_TTScopeDecl;
	_m_parser_TForEachinStmt_OnSemant_m m_OnSemant;
	_m_parser_TForEachinStmt_Trans_m m_Trans;
	_m_type_TLoopStmt_Clear_m m_Clear;
	_m_parser_TForEachinStmt_Create_STTTypeiTTExprTTBlockDeclTTLoopLabelDeclTTExpr_m m_Create_STTTypeiTTExprTTBlockDeclTTLoopLabelDeclTTExpr;
};

struct _m_parser_TForEachinStmt_obj {
	struct BBClass__m_parser_TForEachinStmt* clas;
	BBSTRING __m_type_tstmt_errinfo;
	BBINT __m_type_tstmt_generated;
	struct _m_type_TLoopLabelDecl_obj* __m_type_tloopstmt_looplabel;
	struct _m_type_TBlockDecl_obj* __m_type_tloopstmt_block;
	BBSTRING __m_parser_tforeachinstmt_varid;
	struct _m_type_TType_obj* __m_parser_tforeachinstmt_varty;
	BBINT __m_parser_tforeachinstmt_varlocal;
	struct _m_type_TExpr_obj* __m_parser_tforeachinstmt_expr;
	struct _m_type_TExpr_obj* __m_parser_tforeachinstmt_varexpr;
};
extern struct BBClass__m_parser_TForEachinStmt _m_parser_TForEachinStmt;
void __m_parser_TIncbin_New(struct _m_parser_TIncbin_obj* o);
typedef struct _m_parser_TIncbin_obj* (*_m_parser_TIncbin_Create_SS_m)(struct _m_parser_TIncbin_obj*,BBSTRING,BBSTRING);
struct _m_parser_TIncbin_obj* __m_parser_TIncbin_Create_SS(struct _m_parser_TIncbin_obj*,BBSTRING,BBSTRING);
typedef BBSTRING (*_m_parser_TIncbin_GeneratedDataName_TTAppDecl_m)(struct _m_parser_TIncbin_obj*,struct _m_type_TAppDecl_obj*);
BBSTRING __m_parser_TIncbin_GeneratedDataName_TTAppDecl(struct _m_parser_TIncbin_obj*,struct _m_type_TAppDecl_obj*);
typedef BBSTRING (*_m_parser_TIncbin_GeneratedSizeName_TTAppDecl_m)(struct _m_parser_TIncbin_obj*,struct _m_type_TAppDecl_obj*);
BBSTRING __m_parser_TIncbin_GeneratedSizeName_TTAppDecl(struct _m_parser_TIncbin_obj*,struct _m_type_TAppDecl_obj*);
struct BBClass__m_parser_TIncbin {
	BBClass*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	_m_parser_TIncbin_Create_SS_m m_Create_SS;
	_m_parser_TIncbin_GeneratedDataName_TTAppDecl_m m_GeneratedDataName_TTAppDecl;
	_m_parser_TIncbin_GeneratedSizeName_TTAppDecl_m m_GeneratedSizeName_TTAppDecl;
};

struct _m_parser_TIncbin_obj {
	struct BBClass__m_parser_TIncbin* clas;
	BBSTRING __m_parser_tincbin_file;
	BBSTRING __m_parser_tincbin_path;
	BBINT __m_parser_tincbin_id;
	BBINT __m_parser_tincbin_length;
};
extern struct BBClass__m_parser_TIncbin _m_parser_TIncbin;
extern BBINT _m_parser_TIncbin_count;
void __m_parser_TParser_New(struct _m_parser_TParser_obj* o);
typedef void (*_m_parser_TParser_SetErr_TTToker_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
void __m_parser_TParser_SetErr_TTToker(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
typedef void (*_m_parser_TParser_DoErr_STTToker_m)(struct _m_parser_TParser_obj*,BBSTRING,struct _m_toker_TToker_obj*);
void __m_parser_TParser_DoErr_STTToker(struct _m_parser_TParser_obj*,BBSTRING,struct _m_toker_TToker_obj*);
typedef void (*_m_parser_TParser_PushBlock_TTBlockDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TBlockDecl_obj*);
void __m_parser_TParser_PushBlock_TTBlockDecl(struct _m_parser_TParser_obj*,struct _m_type_TBlockDecl_obj*);
typedef void (*_m_parser_TParser_PopBlock_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_PopBlock(struct _m_parser_TParser_obj*);
typedef BBSTRING (*_m_parser_TParser_RealPath_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
BBSTRING __m_parser_TParser_RealPath_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef BBSTRING (*_m_parser_TParser_ActualPath_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
BBSTRING __m_parser_TParser_ActualPath_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef BBSTRING (*_m_parser_TParser_NextToke_m)(struct _m_parser_TParser_obj*);
BBSTRING __m_parser_TParser_NextToke(struct _m_parser_TParser_obj*);
typedef BBSTRING (*_m_parser_TParser_NextTokeToker_TTToker_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
BBSTRING __m_parser_TParser_NextTokeToker_TTToker(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
typedef BBSTRING (*_m_parser_TParser_DescribeToke_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
BBSTRING __m_parser_TParser_DescribeToke_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef BBINT (*_m_parser_TParser_CParse_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
BBINT __m_parser_TParser_CParse_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef BBINT (*_m_parser_TParser_CParseToker_TTTokerS_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
BBINT __m_parser_TParser_CParseToker_TTTokerS(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
typedef void (*_m_parser_TParser_Parse_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
void __m_parser_TParser_Parse_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef void (*_m_parser_TParser_ParseToker_TTTokerS_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
void __m_parser_TParser_ParseToker_TTTokerS(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,BBSTRING);
typedef BBINT (*_m_parser_TParser_AtEos_m)(struct _m_parser_TParser_obj*);
BBINT __m_parser_TParser_AtEos(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_SkipEols_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_SkipEols(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_SkipEolsToker_TTToker_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
void __m_parser_TParser_SkipEolsToker_TTToker(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
typedef BBSTRING (*_m_parser_TParser_ParseStringLit_m)(struct _m_parser_TParser_obj*);
BBSTRING __m_parser_TParser_ParseStringLit(struct _m_parser_TParser_obj*);
typedef BBSTRING (*_m_parser_TParser_ParseIdent_m)(struct _m_parser_TParser_obj*);
BBSTRING __m_parser_TParser_ParseIdent(struct _m_parser_TParser_obj*);
typedef struct _m_type_TIdentType_obj* (*_m_parser_TParser_ParseIdentType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TIdentType_obj* __m_parser_TParser_ParseIdentType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TIdentType_obj* (*_m_parser_TParser_CParseIdentType_i_m)(struct _m_parser_TParser_obj*,BBINT);
struct _m_type_TIdentType_obj* __m_parser_TParser_CParseIdentType_i(struct _m_parser_TParser_obj*,BBINT);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_CParsePrimitiveType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TType_obj* __m_parser_TParser_CParsePrimitiveType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_CParsePrimitiveNumberType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TType_obj* __m_parser_TParser_CParsePrimitiveNumberType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_ParseNewType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TType_obj* __m_parser_TParser_ParseNewType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_ParseType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TType_obj* __m_parser_TParser_ParseType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_ParseConstNumberType_m)(struct _m_parser_TParser_obj*);
struct _m_type_TType_obj* __m_parser_TParser_ParseConstNumberType(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_ParseDeclType_i_m)(struct _m_parser_TParser_obj*,BBINT);
struct _m_type_TType_obj* __m_parser_TParser_ParseDeclType_i(struct _m_parser_TParser_obj*,BBINT);
typedef struct _m_type_TArrayExpr_obj* (*_m_parser_TParser_ParseArrayExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TArrayExpr_obj* __m_parser_TParser_ParseArrayExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TType_obj* (*_m_parser_TParser_ParseArrayType_TTTypei_m)(struct _m_parser_TParser_obj*,struct _m_type_TType_obj*,BBINT);
struct _m_type_TType_obj* __m_parser_TParser_ParseArrayType_TTTypei(struct _m_parser_TParser_obj*,struct _m_type_TType_obj*,BBINT);
typedef BBINT (*_m_parser_TParser_IsArrayTypeNext_TTToker_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
BBINT __m_parser_TParser_IsArrayTypeNext_TTToker(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*);
typedef BBINT (*_m_parser_TParser_IsArrayDef_i_m)(struct _m_parser_TParser_obj*,BBINT);
BBINT __m_parser_TParser_IsArrayDef_i(struct _m_parser_TParser_obj*,BBINT);
typedef BBARRAY (*_m_parser_TParser_ParseArgs_i_m)(struct _m_parser_TParser_obj*,BBINT);
BBARRAY __m_parser_TParser_ParseArgs_i(struct _m_parser_TParser_obj*,BBINT);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParsePrimaryExpr_i_m)(struct _m_parser_TParser_obj*,BBINT);
struct _m_type_TExpr_obj* __m_parser_TParser_ParsePrimaryExpr_i(struct _m_parser_TParser_obj*,BBINT);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseUnaryExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseUnaryExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParsePowExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParsePowExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseMulDivExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseMulDivExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseAddSubExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseAddSubExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseBitandExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseBitandExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseBitorExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseBitorExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseCompareExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseCompareExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseAndExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseAndExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseOrExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseOrExpr(struct _m_parser_TParser_obj*);
typedef struct _m_type_TExpr_obj* (*_m_parser_TParser_ParseExpr_m)(struct _m_parser_TParser_obj*);
struct _m_type_TExpr_obj* __m_parser_TParser_ParseExpr(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseIfStmt_Si_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
void __m_parser_TParser_ParseIfStmt_Si(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
typedef void (*_m_parser_TParser_ParseWhileStmt_TTLoopLabelDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
void __m_parser_TParser_ParseWhileStmt_TTLoopLabelDecl(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
typedef void (*_m_parser_TParser_ParseRepeatStmt_TTLoopLabelDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
void __m_parser_TParser_ParseRepeatStmt_TTLoopLabelDecl(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
typedef void (*_m_parser_TParser_ParseForStmt_TTLoopLabelDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
void __m_parser_TParser_ParseForStmt_TTLoopLabelDecl(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
typedef void (*_m_parser_TParser_ParseDefDataStmt_TTLoopLabelDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
void __m_parser_TParser_ParseDefDataStmt_TTLoopLabelDecl(struct _m_parser_TParser_obj*,struct _m_type_TLoopLabelDecl_obj*);
typedef void (*_m_parser_TParser_ParseReadDataStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseReadDataStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseRestoreDataStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseRestoreDataStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseReturnStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseReturnStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseExitStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseExitStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseContinueStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseContinueStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseTryStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseTryStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseThrowStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseThrowStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseReleaseStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseReleaseStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseAssertStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseAssertStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseEndStmt_i_m)(struct _m_parser_TParser_obj*,BBINT);
void __m_parser_TParser_ParseEndStmt_i(struct _m_parser_TParser_obj*,BBINT);
typedef void (*_m_parser_TParser_ParseSelectStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseSelectStmt(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseExternBlock_TTModuleDecli_m)(struct _m_parser_TParser_obj*,struct _m_type_TModuleDecl_obj*,BBINT);
void __m_parser_TParser_ParseExternBlock_TTModuleDecli(struct _m_parser_TParser_obj*,struct _m_type_TModuleDecl_obj*,BBINT);
typedef void (*_m_parser_TParser_ParseStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseStmt(struct _m_parser_TParser_obj*);
typedef struct _m_type_TDecl_obj* (*_m_parser_TParser_ParseDecl_Si_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
struct _m_type_TDecl_obj* __m_parser_TParser_ParseDecl_Si(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
typedef struct brl_linkedlist_TList_obj* (*_m_parser_TParser_ParseDecls_Sii_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT,BBINT);
struct brl_linkedlist_TList_obj* __m_parser_TParser_ParseDecls_Sii(struct _m_parser_TParser_obj*,BBSTRING,BBINT,BBINT);
typedef void (*_m_parser_TParser_ParseDeclStmts_iiTTModuleDecl_m)(struct _m_parser_TParser_obj*,BBINT,BBINT,struct _m_type_TModuleDecl_obj*);
void __m_parser_TParser_ParseDeclStmts_iiTTModuleDecl(struct _m_parser_TParser_obj*,BBINT,BBINT,struct _m_type_TModuleDecl_obj*);
typedef struct _m_type_TLoopLabelDecl_obj* (*_m_parser_TParser_ParseLoopLabelDecl_m)(struct _m_parser_TParser_obj*);
struct _m_type_TLoopLabelDecl_obj* __m_parser_TParser_ParseLoopLabelDecl(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_HandleDotsLineConnector_i_m)(struct _m_parser_TParser_obj*,BBINT);
void __m_parser_TParser_HandleDotsLineConnector_i(struct _m_parser_TParser_obj*,BBINT);
typedef struct _m_type_TMetadata_obj* (*_m_parser_TParser_ParseMetaData_m)(struct _m_parser_TParser_obj*);
struct _m_type_TMetadata_obj* __m_parser_TParser_ParseMetaData(struct _m_parser_TParser_obj*);
typedef struct _m_type_TFuncDecl_obj* (*_m_parser_TParser_ParseFuncDecl_SiTTScopeDecl_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT,struct _m_type_TScopeDecl_obj*);
struct _m_type_TFuncDecl_obj* __m_parser_TParser_ParseFuncDecl_SiTTScopeDecl(struct _m_parser_TParser_obj*,BBSTRING,BBINT,struct _m_type_TScopeDecl_obj*);
typedef BBINT (*_m_parser_TParser_ParseCallConvention_i_m)(struct _m_parser_TParser_obj*,BBINT);
BBINT __m_parser_TParser_ParseCallConvention_i(struct _m_parser_TParser_obj*,BBINT);
typedef BBARRAY (*_m_parser_TParser_ParseFuncParamDecl_m)(struct _m_parser_TParser_obj*);
BBARRAY __m_parser_TParser_ParseFuncParamDecl(struct _m_parser_TParser_obj*);
typedef struct _m_type_TEnumDecl_obj* (*_m_parser_TParser_ParseEnumDecl_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
struct _m_type_TEnumDecl_obj* __m_parser_TParser_ParseEnumDecl_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef struct _m_type_TClassDecl_obj* (*_m_parser_TParser_ParseClassDecl_SiTTTemplateDets_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT,struct _m_type_TTemplateDets_obj*);
struct _m_type_TClassDecl_obj* __m_parser_TParser_ParseClassDecl_SiTTTemplateDets(struct _m_parser_TParser_obj*,BBSTRING,BBINT,struct _m_type_TTemplateDets_obj*);
typedef void (*_m_parser_TParser_ParseNativeStmt_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseNativeStmt(struct _m_parser_TParser_obj*);
typedef BBSTRING (*_m_parser_TParser_ParseModuleDecl_Si_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
BBSTRING __m_parser_TParser_ParseModuleDecl_Si(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
typedef BBSTRING (*_m_parser_TParser_ParseModPath_m)(struct _m_parser_TParser_obj*);
BBSTRING __m_parser_TParser_ParseModPath(struct _m_parser_TParser_obj*);
typedef BBSTRING (*_m_parser_TParser_ExtractModIdent_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
BBSTRING __m_parser_TParser_ExtractModIdent_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef void (*_m_parser_TParser_ImportFile_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
void __m_parser_TParser_ImportFile_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef void (*_m_parser_TParser_ImportAllModules_i_m)(struct _m_parser_TParser_obj*,BBINT);
void __m_parser_TParser_ImportAllModules_i(struct _m_parser_TParser_obj*,BBINT);
typedef void (*_m_parser_TParser_ImportModule_Si_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
void __m_parser_TParser_ImportModule_Si(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
typedef void (*_m_parser_TParser_ValidateModIdent_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
void __m_parser_TParser_ValidateModIdent_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef void (*_m_parser_TParser_MungAppDecl_TTAppDecl_m)(struct _m_parser_TParser_obj*,struct _m_type_TAppDecl_obj*);
void __m_parser_TParser_MungAppDecl_TTAppDecl(struct _m_parser_TParser_obj*,struct _m_type_TAppDecl_obj*);
typedef void (*_m_parser_TParser_LoadExternCasts_S_m)(struct _m_parser_TParser_obj*,BBSTRING);
void __m_parser_TParser_LoadExternCasts_S(struct _m_parser_TParser_obj*,BBSTRING);
typedef struct _m_parser_TCastDets_obj* (*_m_parser_TParser_ParseExternCast_SiS_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT,BBSTRING);
struct _m_parser_TCastDets_obj* __m_parser_TParser_ParseExternCast_SiS(struct _m_parser_TParser_obj*,BBSTRING,BBINT,BBSTRING);
typedef BBINT (*_m_parser_TParser_ParseCurrentFile_Si_m)(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
BBINT __m_parser_TParser_ParseCurrentFile_Si(struct _m_parser_TParser_obj*,BBSTRING,BBINT);
typedef BBOBJECT (*_m_parser_TParser_ParseGeneric_TTTemplateRecordTTTemplateDets_m)(struct _m_parser_TParser_obj*,struct _m_config_TTemplateRecord_obj*,struct _m_type_TTemplateDets_obj*);
BBOBJECT __m_parser_TParser_ParseGeneric_TTTemplateRecordTTTemplateDets(struct _m_parser_TParser_obj*,struct _m_config_TTemplateRecord_obj*,struct _m_type_TTemplateDets_obj*);
typedef void (*_m_parser_TParser_ParseMain_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseMain(struct _m_parser_TParser_obj*);
typedef void (*_m_parser_TParser_ParseModule_m)(struct _m_parser_TParser_obj*);
void __m_parser_TParser_ParseModule(struct _m_parser_TParser_obj*);
typedef struct _m_parser_TParser_obj* (*_m_parser_TParser_Create_TTTokerTTAppDecli_m)(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,struct _m_type_TAppDecl_obj*,BBINT);
struct _m_parser_TParser_obj* __m_parser_TParser_Create_TTTokerTTAppDecli(struct _m_parser_TParser_obj*,struct _m_toker_TToker_obj*,struct _m_type_TAppDecl_obj*,BBINT);
struct BBClass__m_parser_TParser {
	struct BBClass__m_type_TGenProcessor*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	_m_parser_TParser_ParseGeneric_TTTemplateRecordTTTemplateDets_m m_ParseGeneric_TTTemplateRecordTTTemplateDets;
	_m_parser_TParser_SetErr_TTToker_m m_SetErr_TTToker;
	_m_parser_TParser_DoErr_STTToker_m m_DoErr_STTToker;
	_m_parser_TParser_PushBlock_TTBlockDecl_m m_PushBlock_TTBlockDecl;
	_m_parser_TParser_PopBlock_m m_PopBlock;
	_m_parser_TParser_RealPath_S_m m_RealPath_S;
	_m_parser_TParser_ActualPath_S_m m_ActualPath_S;
	_m_parser_TParser_NextToke_m m_NextToke;
	_m_parser_TParser_NextTokeToker_TTToker_m m_NextTokeToker_TTToker;
	_m_parser_TParser_DescribeToke_S_m m_DescribeToke_S;
	_m_parser_TParser_CParse_S_m m_CParse_S;
	_m_parser_TParser_CParseToker_TTTokerS_m m_CParseToker_TTTokerS;
	_m_parser_TParser_Parse_S_m m_Parse_S;
	_m_parser_TParser_ParseToker_TTTokerS_m m_ParseToker_TTTokerS;
	_m_parser_TParser_AtEos_m m_AtEos;
	_m_parser_TParser_SkipEols_m m_SkipEols;
	_m_parser_TParser_SkipEolsToker_TTToker_m m_SkipEolsToker_TTToker;
	_m_parser_TParser_ParseStringLit_m m_ParseStringLit;
	_m_parser_TParser_ParseIdent_m m_ParseIdent;
	_m_parser_TParser_ParseIdentType_m m_ParseIdentType;
	_m_parser_TParser_CParseIdentType_i_m m_CParseIdentType_i;
	_m_parser_TParser_CParsePrimitiveType_m m_CParsePrimitiveType;
	_m_parser_TParser_CParsePrimitiveNumberType_m m_CParsePrimitiveNumberType;
	_m_parser_TParser_ParseNewType_m m_ParseNewType;
	_m_parser_TParser_ParseType_m m_ParseType;
	_m_parser_TParser_ParseConstNumberType_m m_ParseConstNumberType;
	_m_parser_TParser_ParseDeclType_i_m m_ParseDeclType_i;
	_m_parser_TParser_ParseArrayExpr_m m_ParseArrayExpr;
	_m_parser_TParser_ParseArrayType_TTTypei_m m_ParseArrayType_TTTypei;
	_m_parser_TParser_IsArrayTypeNext_TTToker_m m_IsArrayTypeNext_TTToker;
	_m_parser_TParser_IsArrayDef_i_m m_IsArrayDef_i;
	_m_parser_TParser_ParseArgs_i_m m_ParseArgs_i;
	_m_parser_TParser_ParsePrimaryExpr_i_m m_ParsePrimaryExpr_i;
	_m_parser_TParser_ParseUnaryExpr_m m_ParseUnaryExpr;
	_m_parser_TParser_ParsePowExpr_m m_ParsePowExpr;
	_m_parser_TParser_ParseMulDivExpr_m m_ParseMulDivExpr;
	_m_parser_TParser_ParseAddSubExpr_m m_ParseAddSubExpr;
	_m_parser_TParser_ParseBitandExpr_m m_ParseBitandExpr;
	_m_parser_TParser_ParseBitorExpr_m m_ParseBitorExpr;
	_m_parser_TParser_ParseCompareExpr_m m_ParseCompareExpr;
	_m_parser_TParser_ParseAndExpr_m m_ParseAndExpr;
	_m_parser_TParser_ParseOrExpr_m m_ParseOrExpr;
	_m_parser_TParser_ParseExpr_m m_ParseExpr;
	_m_parser_TParser_ParseIfStmt_Si_m m_ParseIfStmt_Si;
	_m_parser_TParser_ParseWhileStmt_TTLoopLabelDecl_m m_ParseWhileStmt_TTLoopLabelDecl;
	_m_parser_TParser_ParseRepeatStmt_TTLoopLabelDecl_m m_ParseRepeatStmt_TTLoopLabelDecl;
	_m_parser_TParser_ParseForStmt_TTLoopLabelDecl_m m_ParseForStmt_TTLoopLabelDecl;
	_m_parser_TParser_ParseDefDataStmt_TTLoopLabelDecl_m m_ParseDefDataStmt_TTLoopLabelDecl;
	_m_parser_TParser_ParseReadDataStmt_m m_ParseReadDataStmt;
	_m_parser_TParser_ParseRestoreDataStmt_m m_ParseRestoreDataStmt;
	_m_parser_TParser_ParseReturnStmt_m m_ParseReturnStmt;
	_m_parser_TParser_ParseExitStmt_m m_ParseExitStmt;
	_m_parser_TParser_ParseContinueStmt_m m_ParseContinueStmt;
	_m_parser_TParser_ParseTryStmt_m m_ParseTryStmt;
	_m_parser_TParser_ParseThrowStmt_m m_ParseThrowStmt;
	_m_parser_TParser_ParseReleaseStmt_m m_ParseReleaseStmt;
	_m_parser_TParser_ParseAssertStmt_m m_ParseAssertStmt;
	_m_parser_TParser_ParseEndStmt_i_m m_ParseEndStmt_i;
	_m_parser_TParser_ParseSelectStmt_m m_ParseSelectStmt;
	_m_parser_TParser_ParseExternBlock_TTModuleDecli_m m_ParseExternBlock_TTModuleDecli;
	_m_parser_TParser_ParseStmt_m m_ParseStmt;
	_m_parser_TParser_ParseDecl_Si_m m_ParseDecl_Si;
	_m_parser_TParser_ParseDecls_Sii_m m_ParseDecls_Sii;
	_m_parser_TParser_ParseDeclStmts_iiTTModuleDecl_m m_ParseDeclStmts_iiTTModuleDecl;
	_m_parser_TParser_ParseLoopLabelDecl_m m_ParseLoopLabelDecl;
	_m_parser_TParser_HandleDotsLineConnector_i_m m_HandleDotsLineConnector_i;
	_m_parser_TParser_ParseMetaData_m m_ParseMetaData;
	_m_parser_TParser_ParseFuncDecl_SiTTScopeDecl_m m_ParseFuncDecl_SiTTScopeDecl;
	_m_parser_TParser_ParseCallConvention_i_m m_ParseCallConvention_i;
	_m_parser_TParser_ParseFuncParamDecl_m m_ParseFuncParamDecl;
	_m_parser_TParser_ParseEnumDecl_S_m m_ParseEnumDecl_S;
	_m_parser_TParser_ParseClassDecl_SiTTTemplateDets_m m_ParseClassDecl_SiTTTemplateDets;
	_m_parser_TParser_ParseNativeStmt_m m_ParseNativeStmt;
	_m_parser_TParser_ParseModuleDecl_Si_m m_ParseModuleDecl_Si;
	_m_parser_TParser_ParseModPath_m m_ParseModPath;
	_m_parser_TParser_ExtractModIdent_S_m m_ExtractModIdent_S;
	_m_parser_TParser_ImportFile_S_m m_ImportFile_S;
	_m_parser_TParser_ImportAllModules_i_m m_ImportAllModules_i;
	_m_parser_TParser_ImportModule_Si_m m_ImportModule_Si;
	_m_parser_TParser_ValidateModIdent_S_m m_ValidateModIdent_S;
	_m_parser_TParser_MungAppDecl_TTAppDecl_m m_MungAppDecl_TTAppDecl;
	_m_parser_TParser_LoadExternCasts_S_m m_LoadExternCasts_S;
	_m_parser_TParser_ParseExternCast_SiS_m m_ParseExternCast_SiS;
	_m_parser_TParser_ParseCurrentFile_Si_m m_ParseCurrentFile_Si;
	_m_parser_TParser_ParseMain_m m_ParseMain;
	_m_parser_TParser_ParseModule_m m_ParseModule;
	_m_parser_TParser_Create_TTTokerTTAppDecli_m m_Create_TTTokerTTAppDecli;
};

struct _m_parser_TParser_obj {
	struct BBClass__m_parser_TParser* clas;
	struct _m_toker_TToker_obj* __m_parser_tparser__toker;
	BBSTRING __m_parser_tparser__toke;
	BBINT __m_parser_tparser__toketype;
	struct _m_type_TBlockDecl_obj* __m_parser_tparser__block;
	struct brl_linkedlist_TList_obj* __m_parser_tparser__blockstack;
	struct _m_config_TStringList_obj* __m_parser_tparser__errstack;
	struct _m_type_TAppDecl_obj* __m_parser_tparser__app;
	struct _m_type_TModuleDecl_obj* __m_parser_tparser__module;
	struct brl_map_TMap_obj* __m_parser_tparser__externcasts;
	BBINT __m_parser_tparser_unknownidentsevalfalse;
};
extern struct BBClass__m_parser_TParser _m_parser_TParser;
void __m_parser_TCastDets_New(struct _m_parser_TCastDets_obj* o);
struct BBClass__m_parser_TCastDets {
	BBClass*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
};

struct _m_parser_TCastDets_obj {
	struct BBClass__m_parser_TCastDets* clas;
	BBSTRING __m_parser_tcastdets_name;
	BBSTRING __m_parser_tcastdets_rettype;
	BBINT __m_parser_tcastdets_nogen;
	BBARRAY __m_parser_tcastdets_args;
	BBSTRING __m_parser_tcastdets_api;
};
extern struct BBClass__m_parser_TCastDets _m_parser_TCastDets;
BBSTRING _m_parser_EvalS(BBSTRING bbt_source,struct _m_type_TType_obj* bbt_ty);
BBSTRING _m_parser_Eval(struct _m_toker_TToker_obj* bbt_toker,struct _m_type_TType_obj* bbt__type);
BBSTRING _m_parser_PreProcessNextToke(struct _m_toker_TToker_obj* bbt_toker);
BBSTRING _m_parser_PreProcess(BBSTRING bbt_path);
BBSTRING _m_parser_MungModuleName(BBOBJECT bbt_ident);
struct _m_type_TModuleDecl_obj* _m_parser_ParseModule(BBSTRING bbt_path,struct _m_type_TAppDecl_obj* bbt_app);
BBSTRING _m_parser_AppendLibInit(BBSTRING bbt_source);
struct _m_type_TAppDecl_obj* _m_parser_ParseApp(BBSTRING bbt_path);

#endif
