#ifndef BRL_REFLECTION_REFLECTION_BMX_RELEASE_HAIKU_X64_H
#define BRL_REFLECTION_REFLECTION_BMX_RELEASE_HAIKU_X64_H

#include <brl.mod/blitz.mod/.bmx/blitz.bmx.release.haiku.x64.h>
#include <brl.mod/linkedlist.mod/.bmx/linkedlist.bmx.release.haiku.x64.h>
#include <brl.mod/map.mod/.bmx/map.bmx.release.haiku.x64.h>
#include <brl.mod/threads.mod/.bmx/threads.bmx.release.haiku.x64.h>
#include <brl.mod/stringbuilder.mod/.bmx/stringbuilder.bmx.release.haiku.x64.h>
int __bb_brl_reflection_reflection();
struct brl_reflection_TTypeId_obj;
struct brl_reflection_TMember_obj;
struct brl_reflection_TConstant_obj;
struct brl_reflection_TField_obj;
struct brl_reflection_TGlobal_obj;
struct brl_reflection_TFunction_obj;
struct brl_reflection_TMethod_obj;
void _brl_reflection_TTypeId_New(struct brl_reflection_TTypeId_obj* o);
typedef BBSTRING (*brl_reflection_TTypeId_Name_m)(struct brl_reflection_TTypeId_obj*);
BBSTRING _brl_reflection_TTypeId_Name(struct brl_reflection_TTypeId_obj*);
typedef BBSTRING (*brl_reflection_TTypeId_MetaData_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
BBSTRING _brl_reflection_TTypeId_MetaData_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef BBINT (*brl_reflection_TTypeId_HasMetaData_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
BBINT _brl_reflection_TTypeId_HasMetaData_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_SuperType_m)(struct brl_reflection_TTypeId_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_SuperType(struct brl_reflection_TTypeId_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_ArrayType_i_m)(struct brl_reflection_TTypeId_obj*,BBINT);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_ArrayType_i(struct brl_reflection_TTypeId_obj*,BBINT);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_ElementType_m)(struct brl_reflection_TTypeId_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_ElementType(struct brl_reflection_TTypeId_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_PointerType_m)(struct brl_reflection_TTypeId_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_PointerType(struct brl_reflection_TTypeId_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_FunctionType_aTTTypeId_m)(struct brl_reflection_TTypeId_obj*,BBARRAY);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_FunctionType_aTTTypeId(struct brl_reflection_TTypeId_obj*,BBARRAY);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_ReturnType_m)(struct brl_reflection_TTypeId_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_ReturnType(struct brl_reflection_TTypeId_obj*);
typedef BBARRAY (*brl_reflection_TTypeId_ArgTypes_m)(struct brl_reflection_TTypeId_obj*);
BBARRAY _brl_reflection_TTypeId_ArgTypes(struct brl_reflection_TTypeId_obj*);
typedef BBINT (*brl_reflection_TTypeId_ExtendsType_TTTypeId_m)(struct brl_reflection_TTypeId_obj*,struct brl_reflection_TTypeId_obj*);
BBINT _brl_reflection_TTypeId_ExtendsType_TTTypeId(struct brl_reflection_TTypeId_obj*,struct brl_reflection_TTypeId_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_DerivedTypes_m)(struct brl_reflection_TTypeId_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_DerivedTypes(struct brl_reflection_TTypeId_obj*);
typedef BBOBJECT (*brl_reflection_TTypeId_NewObject_m)(struct brl_reflection_TTypeId_obj*);
BBOBJECT _brl_reflection_TTypeId_NewObject(struct brl_reflection_TTypeId_obj*);
typedef BBINT (*brl_reflection_TTypeId_IsInterface_m)(struct brl_reflection_TTypeId_obj*);
BBINT _brl_reflection_TTypeId_IsInterface(struct brl_reflection_TTypeId_obj*);
typedef struct brl_map_stringmap_TStringMap_obj* (*brl_reflection_TTypeId_Constants_m)(struct brl_reflection_TTypeId_obj*);
struct brl_map_stringmap_TStringMap_obj* _brl_reflection_TTypeId_Constants(struct brl_reflection_TTypeId_obj*);
typedef struct brl_map_stringmap_TStringMap_obj* (*brl_reflection_TTypeId_Fields_m)(struct brl_reflection_TTypeId_obj*);
struct brl_map_stringmap_TStringMap_obj* _brl_reflection_TTypeId_Fields(struct brl_reflection_TTypeId_obj*);
typedef struct brl_map_stringmap_TStringMap_obj* (*brl_reflection_TTypeId_Globals_m)(struct brl_reflection_TTypeId_obj*);
struct brl_map_stringmap_TStringMap_obj* _brl_reflection_TTypeId_Globals(struct brl_reflection_TTypeId_obj*);
typedef struct brl_map_stringmap_TStringMap_obj* (*brl_reflection_TTypeId_Functions_m)(struct brl_reflection_TTypeId_obj*);
struct brl_map_stringmap_TStringMap_obj* _brl_reflection_TTypeId_Functions(struct brl_reflection_TTypeId_obj*);
typedef struct brl_map_stringmap_TStringMap_obj* (*brl_reflection_TTypeId_Methods_m)(struct brl_reflection_TTypeId_obj*);
struct brl_map_stringmap_TStringMap_obj* _brl_reflection_TTypeId_Methods(struct brl_reflection_TTypeId_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_Interfaces_m)(struct brl_reflection_TTypeId_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_Interfaces(struct brl_reflection_TTypeId_obj*);
typedef struct brl_reflection_TConstant_obj* (*brl_reflection_TTypeId_FindConstant_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
struct brl_reflection_TConstant_obj* _brl_reflection_TTypeId_FindConstant_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TField_obj* (*brl_reflection_TTypeId_FindField_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
struct brl_reflection_TField_obj* _brl_reflection_TTypeId_FindField_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TGlobal_obj* (*brl_reflection_TTypeId_FindGlobal_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
struct brl_reflection_TGlobal_obj* _brl_reflection_TTypeId_FindGlobal_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TFunction_obj* (*brl_reflection_TTypeId_FindFunction_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
struct brl_reflection_TFunction_obj* _brl_reflection_TTypeId_FindFunction_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TMethod_obj* (*brl_reflection_TTypeId_FindMethod_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
struct brl_reflection_TMethod_obj* _brl_reflection_TTypeId_FindMethod_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumConstants_TTList_m)(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_EnumConstants_TTList(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumFields_TTList_m)(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_EnumFields_TTList(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumGlobals_TTList_m)(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_EnumGlobals_TTList(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumFunctions_TTList_m)(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_EnumFunctions_TTList(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumMethods_TTList_m)(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
struct brl_linkedlist_TList_obj* _brl_reflection_TTypeId_EnumMethods_TTList(struct brl_reflection_TTypeId_obj*,struct brl_linkedlist_TList_obj*);
typedef BBOBJECT (*brl_reflection_TTypeId_NewArray_iai_m)(struct brl_reflection_TTypeId_obj*,BBINT,BBARRAY);
BBOBJECT _brl_reflection_TTypeId_NewArray_iai(struct brl_reflection_TTypeId_obj*,BBINT,BBARRAY);
typedef BBINT (*brl_reflection_TTypeId_ArrayLength_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBINT _brl_reflection_TTypeId_ArrayLength_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBOBJECT (*brl_reflection_TTypeId_NullArray_m)(struct brl_reflection_TTypeId_obj*);
BBOBJECT _brl_reflection_TTypeId_NullArray(struct brl_reflection_TTypeId_obj*);
typedef BBINT (*brl_reflection_TTypeId_ArrayDimensions_TObject_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT);
BBINT _brl_reflection_TTypeId_ArrayDimensions_TObject(struct brl_reflection_TTypeId_obj*,BBOBJECT);
typedef BBOBJECT (*brl_reflection_TTypeId_ArraySlice_TObjectii_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
BBOBJECT _brl_reflection_TTypeId_ArraySlice_TObjectii(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
typedef BBOBJECT (*brl_reflection_TTypeId_GetArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBOBJECT _brl_reflection_TTypeId_GetArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBSTRING (*brl_reflection_TTypeId_GetStringArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBSTRING _brl_reflection_TTypeId_GetStringArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBBYTE (*brl_reflection_TTypeId_GetByteArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBBYTE _brl_reflection_TTypeId_GetByteArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBSHORT (*brl_reflection_TTypeId_GetShortArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBSHORT _brl_reflection_TTypeId_GetShortArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBINT (*brl_reflection_TTypeId_GetIntArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBINT _brl_reflection_TTypeId_GetIntArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBUINT (*brl_reflection_TTypeId_GetUIntArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBUINT _brl_reflection_TTypeId_GetUIntArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBLONG (*brl_reflection_TTypeId_GetLongArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBLONG _brl_reflection_TTypeId_GetLongArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBULONG (*brl_reflection_TTypeId_GetULongArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBULONG _brl_reflection_TTypeId_GetULongArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBSIZET (*brl_reflection_TTypeId_GetSizeTArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBSIZET _brl_reflection_TTypeId_GetSizeTArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBFLOAT (*brl_reflection_TTypeId_GetFloatArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBFLOAT _brl_reflection_TTypeId_GetFloatArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBDOUBLE (*brl_reflection_TTypeId_GetDoubleArrayElement_TObjecti_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
BBDOUBLE _brl_reflection_TTypeId_GetDoubleArrayElement_TObjecti(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectiTObject_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBOBJECT);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectiTObject(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBOBJECT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectib_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBBYTE);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectib(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBBYTE);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectis_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSHORT);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectis(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSHORT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectii_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectii(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectiu_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBUINT);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectiu(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBUINT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectil_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBLONG);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectil(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBLONG);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectiy_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBULONG);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectiy(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBULONG);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectiz_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSIZET);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectiz(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSIZET);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectif_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBFLOAT);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectif(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBFLOAT);
typedef BBINT (*brl_reflection_TTypeId_SetArrayElement_TObjectid_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBDOUBLE);
BBINT _brl_reflection_TTypeId_SetArrayElement_TObjectid(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBDOUBLE);
typedef BBINT (*brl_reflection_TTypeId_SetByteArrayElement_TObjectib_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBBYTE);
BBINT _brl_reflection_TTypeId_SetByteArrayElement_TObjectib(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBBYTE);
typedef BBINT (*brl_reflection_TTypeId_SetShortArrayElement_TObjectis_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSHORT);
BBINT _brl_reflection_TTypeId_SetShortArrayElement_TObjectis(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSHORT);
typedef BBINT (*brl_reflection_TTypeId_SetIntArrayElement_TObjectii_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
BBINT _brl_reflection_TTypeId_SetIntArrayElement_TObjectii(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBINT);
typedef BBINT (*brl_reflection_TTypeId_SetUIntArrayElement_TObjectiu_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBUINT);
BBINT _brl_reflection_TTypeId_SetUIntArrayElement_TObjectiu(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBUINT);
typedef BBINT (*brl_reflection_TTypeId_SetLongArrayElement_TObjectil_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBLONG);
BBINT _brl_reflection_TTypeId_SetLongArrayElement_TObjectil(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBLONG);
typedef BBINT (*brl_reflection_TTypeId_SetULongArrayElement_TObjectiy_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBULONG);
BBINT _brl_reflection_TTypeId_SetULongArrayElement_TObjectiy(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBULONG);
typedef BBINT (*brl_reflection_TTypeId_SetSizeTArrayElement_TObjectiz_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSIZET);
BBINT _brl_reflection_TTypeId_SetSizeTArrayElement_TObjectiz(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSIZET);
typedef BBINT (*brl_reflection_TTypeId_SetFloatArrayElement_TObjectif_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBFLOAT);
BBINT _brl_reflection_TTypeId_SetFloatArrayElement_TObjectif(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBFLOAT);
typedef BBINT (*brl_reflection_TTypeId_SetDoubleArrayElement_TObjectid_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBDOUBLE);
BBINT _brl_reflection_TTypeId_SetDoubleArrayElement_TObjectid(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBDOUBLE);
typedef BBINT (*brl_reflection_TTypeId_SetStringArrayElement_TObjectiS_m)(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSTRING);
BBINT _brl_reflection_TTypeId_SetStringArrayElement_TObjectiS(struct brl_reflection_TTypeId_obj*,BBOBJECT,BBINT,BBSTRING);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_ForName_TTTypeId_S_f)(BBSTRING);
struct brl_reflection_TTypeId_obj* brl_reflection_TTypeId_ForName_TTTypeId_S(BBSTRING);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_ForObject_TTTypeId_TObject_f)(BBOBJECT);
struct brl_reflection_TTypeId_obj* brl_reflection_TTypeId_ForObject_TTTypeId_TObject(BBOBJECT);
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumTypes_TTList_f)();
struct brl_linkedlist_TList_obj* brl_reflection_TTypeId_EnumTypes_TTList();
typedef struct brl_linkedlist_TList_obj* (*brl_reflection_TTypeId_EnumInterfaces_TTList_f)();
struct brl_linkedlist_TList_obj* brl_reflection_TTypeId_EnumInterfaces_TTList();
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_Init_SipbTTTypeId_m)(struct brl_reflection_TTypeId_obj*,BBSTRING,BBINT,BBBYTE*,struct brl_reflection_TTypeId_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_Init_SipbTTTypeId(struct brl_reflection_TTypeId_obj*,BBSTRING,BBINT,BBBYTE*,struct brl_reflection_TTypeId_obj*);
typedef BBINT (*brl_reflection_TTypeId_InitMeta_S_m)(struct brl_reflection_TTypeId_obj*,BBSTRING);
BBINT _brl_reflection_TTypeId_InitMeta_S(struct brl_reflection_TTypeId_obj*,BBSTRING);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_SetClass_pb_m)(struct brl_reflection_TTypeId_obj*,BBBYTE*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_SetClass_pb(struct brl_reflection_TTypeId_obj*,BBBYTE*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TTypeId_SetInterface_pb_m)(struct brl_reflection_TTypeId_obj*,BBBYTE*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TTypeId_SetInterface_pb(struct brl_reflection_TTypeId_obj*,BBBYTE*);
typedef BBINT (*brl_reflection_TTypeId__Update_i_f)();
BBINT brl_reflection_TTypeId__Update_i();
typedef BBINT (*brl_reflection_TTypeId__UpdateInterfaces_i_f)();
BBINT brl_reflection_TTypeId__UpdateInterfaces_i();
typedef BBINT (*brl_reflection_TTypeId__Resolve_m)(struct brl_reflection_TTypeId_obj*);
BBINT _brl_reflection_TTypeId__Resolve(struct brl_reflection_TTypeId_obj*);
struct BBClass_brl_reflection_TTypeId {
	BBClass*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TTypeId_Name_m m_Name;
	brl_reflection_TTypeId_MetaData_S_m m_MetaData_S;
	brl_reflection_TTypeId_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TTypeId_SuperType_m m_SuperType;
	brl_reflection_TTypeId_ArrayType_i_m m_ArrayType_i;
	brl_reflection_TTypeId_ElementType_m m_ElementType;
	brl_reflection_TTypeId_PointerType_m m_PointerType;
	brl_reflection_TTypeId_FunctionType_aTTTypeId_m m_FunctionType_aTTTypeId;
	brl_reflection_TTypeId_ReturnType_m m_ReturnType;
	brl_reflection_TTypeId_ArgTypes_m m_ArgTypes;
	brl_reflection_TTypeId_ExtendsType_TTTypeId_m m_ExtendsType_TTTypeId;
	brl_reflection_TTypeId_DerivedTypes_m m_DerivedTypes;
	brl_reflection_TTypeId_NewObject_m m_NewObject;
	brl_reflection_TTypeId_IsInterface_m m_IsInterface;
	brl_reflection_TTypeId_Constants_m m_Constants;
	brl_reflection_TTypeId_Fields_m m_Fields;
	brl_reflection_TTypeId_Globals_m m_Globals;
	brl_reflection_TTypeId_Functions_m m_Functions;
	brl_reflection_TTypeId_Methods_m m_Methods;
	brl_reflection_TTypeId_Interfaces_m m_Interfaces;
	brl_reflection_TTypeId_FindConstant_S_m m_FindConstant_S;
	brl_reflection_TTypeId_FindField_S_m m_FindField_S;
	brl_reflection_TTypeId_FindGlobal_S_m m_FindGlobal_S;
	brl_reflection_TTypeId_FindFunction_S_m m_FindFunction_S;
	brl_reflection_TTypeId_FindMethod_S_m m_FindMethod_S;
	brl_reflection_TTypeId_EnumConstants_TTList_m m_EnumConstants_TTList;
	brl_reflection_TTypeId_EnumFields_TTList_m m_EnumFields_TTList;
	brl_reflection_TTypeId_EnumGlobals_TTList_m m_EnumGlobals_TTList;
	brl_reflection_TTypeId_EnumFunctions_TTList_m m_EnumFunctions_TTList;
	brl_reflection_TTypeId_EnumMethods_TTList_m m_EnumMethods_TTList;
	brl_reflection_TTypeId_NewArray_iai_m m_NewArray_iai;
	brl_reflection_TTypeId_ArrayLength_TObjecti_m m_ArrayLength_TObjecti;
	brl_reflection_TTypeId_NullArray_m m_NullArray;
	brl_reflection_TTypeId_ArrayDimensions_TObject_m m_ArrayDimensions_TObject;
	brl_reflection_TTypeId_ArraySlice_TObjectii_m m_ArraySlice_TObjectii;
	brl_reflection_TTypeId_GetArrayElement_TObjecti_m m_GetArrayElement_TObjecti;
	brl_reflection_TTypeId_GetStringArrayElement_TObjecti_m m_GetStringArrayElement_TObjecti;
	brl_reflection_TTypeId_GetByteArrayElement_TObjecti_m m_GetByteArrayElement_TObjecti;
	brl_reflection_TTypeId_GetShortArrayElement_TObjecti_m m_GetShortArrayElement_TObjecti;
	brl_reflection_TTypeId_GetIntArrayElement_TObjecti_m m_GetIntArrayElement_TObjecti;
	brl_reflection_TTypeId_GetUIntArrayElement_TObjecti_m m_GetUIntArrayElement_TObjecti;
	brl_reflection_TTypeId_GetLongArrayElement_TObjecti_m m_GetLongArrayElement_TObjecti;
	brl_reflection_TTypeId_GetULongArrayElement_TObjecti_m m_GetULongArrayElement_TObjecti;
	brl_reflection_TTypeId_GetSizeTArrayElement_TObjecti_m m_GetSizeTArrayElement_TObjecti;
	brl_reflection_TTypeId_GetFloatArrayElement_TObjecti_m m_GetFloatArrayElement_TObjecti;
	brl_reflection_TTypeId_GetDoubleArrayElement_TObjecti_m m_GetDoubleArrayElement_TObjecti;
	brl_reflection_TTypeId_SetArrayElement_TObjectiTObject_m m_SetArrayElement_TObjectiTObject;
	brl_reflection_TTypeId_SetArrayElement_TObjectib_m m_SetArrayElement_TObjectib;
	brl_reflection_TTypeId_SetArrayElement_TObjectis_m m_SetArrayElement_TObjectis;
	brl_reflection_TTypeId_SetArrayElement_TObjectii_m m_SetArrayElement_TObjectii;
	brl_reflection_TTypeId_SetArrayElement_TObjectiu_m m_SetArrayElement_TObjectiu;
	brl_reflection_TTypeId_SetArrayElement_TObjectil_m m_SetArrayElement_TObjectil;
	brl_reflection_TTypeId_SetArrayElement_TObjectiy_m m_SetArrayElement_TObjectiy;
	brl_reflection_TTypeId_SetArrayElement_TObjectiz_m m_SetArrayElement_TObjectiz;
	brl_reflection_TTypeId_SetArrayElement_TObjectif_m m_SetArrayElement_TObjectif;
	brl_reflection_TTypeId_SetArrayElement_TObjectid_m m_SetArrayElement_TObjectid;
	brl_reflection_TTypeId_SetByteArrayElement_TObjectib_m m_SetByteArrayElement_TObjectib;
	brl_reflection_TTypeId_SetShortArrayElement_TObjectis_m m_SetShortArrayElement_TObjectis;
	brl_reflection_TTypeId_SetIntArrayElement_TObjectii_m m_SetIntArrayElement_TObjectii;
	brl_reflection_TTypeId_SetUIntArrayElement_TObjectiu_m m_SetUIntArrayElement_TObjectiu;
	brl_reflection_TTypeId_SetLongArrayElement_TObjectil_m m_SetLongArrayElement_TObjectil;
	brl_reflection_TTypeId_SetULongArrayElement_TObjectiy_m m_SetULongArrayElement_TObjectiy;
	brl_reflection_TTypeId_SetSizeTArrayElement_TObjectiz_m m_SetSizeTArrayElement_TObjectiz;
	brl_reflection_TTypeId_SetFloatArrayElement_TObjectif_m m_SetFloatArrayElement_TObjectif;
	brl_reflection_TTypeId_SetDoubleArrayElement_TObjectid_m m_SetDoubleArrayElement_TObjectid;
	brl_reflection_TTypeId_SetStringArrayElement_TObjectiS_m m_SetStringArrayElement_TObjectiS;
	brl_reflection_TTypeId_ForName_TTTypeId_S_f f_ForName_TTTypeId_S;
	brl_reflection_TTypeId_ForObject_TTTypeId_TObject_f f_ForObject_TTTypeId_TObject;
	brl_reflection_TTypeId_EnumTypes_TTList_f f_EnumTypes_TTList;
	brl_reflection_TTypeId_EnumInterfaces_TTList_f f_EnumInterfaces_TTList;
	brl_reflection_TTypeId_Init_SipbTTTypeId_m m_Init_SipbTTTypeId;
	brl_reflection_TTypeId_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TTypeId_SetClass_pb_m m_SetClass_pb;
	brl_reflection_TTypeId_SetInterface_pb_m m_SetInterface_pb;
	brl_reflection_TTypeId__Update_i_f f__Update_i;
	brl_reflection_TTypeId__UpdateInterfaces_i_f f__UpdateInterfaces_i;
	brl_reflection_TTypeId__Resolve_m m__Resolve;
};

struct brl_reflection_TTypeId_obj {
	struct BBClass_brl_reflection_TTypeId* clas;
	BBSTRING _brl_reflection_ttypeid__name;
	BBSTRING _brl_reflection_ttypeid__meta;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__metamap;
	BBBYTE* _brl_reflection_ttypeid__class;
	BBBYTE* _brl_reflection_ttypeid__interface;
	BBINT _brl_reflection_ttypeid__size;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__consts;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__fields;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__globals;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__functions;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__methods;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__constslist;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__fieldslist;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__globalslist;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__functionslist;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__methodslist;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__interfaces;
	struct brl_reflection_TTypeId_obj* _brl_reflection_ttypeid__super;
	struct brl_linkedlist_TList_obj* _brl_reflection_ttypeid__derived;
	BBARRAY _brl_reflection_ttypeid__arraytype;
	struct brl_reflection_TTypeId_obj* _brl_reflection_ttypeid__elementtype;
	BBBYTE* _brl_reflection_ttypeid__typetag;
	struct brl_reflection_TTypeId_obj* _brl_reflection_ttypeid__pointertype;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_ttypeid__functiontype;
	BBARRAY _brl_reflection_ttypeid__argtypes;
	struct brl_reflection_TTypeId_obj* _brl_reflection_ttypeid__rettype;
};
extern struct BBClass_brl_reflection_TTypeId brl_reflection_TTypeId;
extern BBINT brl_reflection_TTypeId__count;
extern struct brl_map_TMap_obj* brl_reflection_TTypeId__nameMap;
extern struct brl_map_ptrmap_TPtrMap_obj* brl_reflection_TTypeId__classMap;
extern BBINT brl_reflection_TTypeId__icount;
extern struct brl_map_ptrmap_TPtrMap_obj* brl_reflection_TTypeId__interfaceMap;
extern struct brl_reflection_TTypeId_obj* brl_reflection_ByteTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_ShortTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_IntTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_UIntTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_LongTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_ULongTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_SizetTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_FloatTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_DoubleTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_ObjectTypeId;
extern BBBYTE* bbRefObjectClass();
extern struct brl_reflection_TTypeId_obj* brl_reflection_StringTypeId;
extern BBBYTE* bbRefStringClass();
extern struct brl_reflection_TTypeId_obj* brl_reflection_ArrayTypeId;
extern BBBYTE* bbRefArrayClass();
extern struct brl_reflection_TTypeId_obj* brl_reflection_VoidTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_PointerTypeId;
extern struct brl_reflection_TTypeId_obj* brl_reflection_FunctionTypeId;
void _brl_reflection_TMember_New(struct brl_reflection_TMember_obj* o);
typedef BBSTRING (*brl_reflection_TMember_Name_m)(struct brl_reflection_TMember_obj*);
BBSTRING _brl_reflection_TMember_Name(struct brl_reflection_TMember_obj*);
typedef BBSTRING (*brl_reflection_TMember_NameLower_m)(struct brl_reflection_TMember_obj*);
BBSTRING _brl_reflection_TMember_NameLower(struct brl_reflection_TMember_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TMember_TypeId_m)(struct brl_reflection_TMember_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TMember_TypeId(struct brl_reflection_TMember_obj*);
typedef BBSTRING (*brl_reflection_TMember_MetaData_S_m)(struct brl_reflection_TMember_obj*,BBSTRING);
BBSTRING _brl_reflection_TMember_MetaData_S(struct brl_reflection_TMember_obj*,BBSTRING);
typedef BBINT (*brl_reflection_TMember_HasMetaData_S_m)(struct brl_reflection_TMember_obj*,BBSTRING);
BBINT _brl_reflection_TMember_HasMetaData_S(struct brl_reflection_TMember_obj*,BBSTRING);
typedef BBINT (*brl_reflection_TMember_InitMeta_S_m)(struct brl_reflection_TMember_obj*,BBSTRING);
BBINT _brl_reflection_TMember_InitMeta_S(struct brl_reflection_TMember_obj*,BBSTRING);
struct BBClass_brl_reflection_TMember {
	BBClass*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
};

struct brl_reflection_TMember_obj {
	struct BBClass_brl_reflection_TMember* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
};
extern struct BBClass_brl_reflection_TMember brl_reflection_TMember;
void _brl_reflection_TConstant_New(struct brl_reflection_TConstant_obj* o);
typedef struct brl_reflection_TConstant_obj* (*brl_reflection_TConstant_Init_STTTypeIdSS_m)(struct brl_reflection_TConstant_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBSTRING);
struct brl_reflection_TConstant_obj* _brl_reflection_TConstant_Init_STTTypeIdSS(struct brl_reflection_TConstant_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBSTRING);
typedef BBSTRING (*brl_reflection_TConstant_GetString_m)(struct brl_reflection_TConstant_obj*);
BBSTRING _brl_reflection_TConstant_GetString(struct brl_reflection_TConstant_obj*);
typedef BBINT (*brl_reflection_TConstant_GetInt_m)(struct brl_reflection_TConstant_obj*);
BBINT _brl_reflection_TConstant_GetInt(struct brl_reflection_TConstant_obj*);
typedef BBINT (*brl_reflection_TConstant_GetFloat_m)(struct brl_reflection_TConstant_obj*);
BBINT _brl_reflection_TConstant_GetFloat(struct brl_reflection_TConstant_obj*);
typedef BBLONG (*brl_reflection_TConstant_GetLong_m)(struct brl_reflection_TConstant_obj*);
BBLONG _brl_reflection_TConstant_GetLong(struct brl_reflection_TConstant_obj*);
typedef BBSIZET (*brl_reflection_TConstant_GetSizet_m)(struct brl_reflection_TConstant_obj*);
BBSIZET _brl_reflection_TConstant_GetSizet(struct brl_reflection_TConstant_obj*);
typedef BBINT (*brl_reflection_TConstant_GetDouble_m)(struct brl_reflection_TConstant_obj*);
BBINT _brl_reflection_TConstant_GetDouble(struct brl_reflection_TConstant_obj*);
typedef BBBYTE* (*brl_reflection_TConstant_GetPointer_m)(struct brl_reflection_TConstant_obj*);
BBBYTE* _brl_reflection_TConstant_GetPointer(struct brl_reflection_TConstant_obj*);
struct BBClass_brl_reflection_TConstant {
	struct BBClass_brl_reflection_TMember*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TConstant_Init_STTTypeIdSS_m m_Init_STTTypeIdSS;
	brl_reflection_TConstant_GetString_m m_GetString;
	brl_reflection_TConstant_GetInt_m m_GetInt;
	brl_reflection_TConstant_GetFloat_m m_GetFloat;
	brl_reflection_TConstant_GetLong_m m_GetLong;
	brl_reflection_TConstant_GetSizet_m m_GetSizet;
	brl_reflection_TConstant_GetDouble_m m_GetDouble;
	brl_reflection_TConstant_GetPointer_m m_GetPointer;
};

struct brl_reflection_TConstant_obj {
	struct BBClass_brl_reflection_TConstant* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
	BBSTRING _brl_reflection_tconstant__string;
};
extern struct BBClass_brl_reflection_TConstant brl_reflection_TConstant;
void _brl_reflection_TField_New(struct brl_reflection_TField_obj* o);
typedef struct brl_reflection_TField_obj* (*brl_reflection_TField_Init_STTTypeIdSi_m)(struct brl_reflection_TField_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBINT);
struct brl_reflection_TField_obj* _brl_reflection_TField_Init_STTTypeIdSi(struct brl_reflection_TField_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBINT);
typedef BBOBJECT (*brl_reflection_TField_Get_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBOBJECT _brl_reflection_TField_Get_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBBYTE (*brl_reflection_TField_GetByte_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBBYTE _brl_reflection_TField_GetByte_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBSHORT (*brl_reflection_TField_GetShort_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBSHORT _brl_reflection_TField_GetShort_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBINT (*brl_reflection_TField_GetInt_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBINT _brl_reflection_TField_GetInt_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBUINT (*brl_reflection_TField_GetUInt_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBUINT _brl_reflection_TField_GetUInt_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBLONG (*brl_reflection_TField_GetLong_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBLONG _brl_reflection_TField_GetLong_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBULONG (*brl_reflection_TField_GetULong_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBULONG _brl_reflection_TField_GetULong_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBSIZET (*brl_reflection_TField_GetSizet_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBSIZET _brl_reflection_TField_GetSizet_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBFLOAT (*brl_reflection_TField_GetFloat_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBFLOAT _brl_reflection_TField_GetFloat_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBDOUBLE (*brl_reflection_TField_GetDouble_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBDOUBLE _brl_reflection_TField_GetDouble_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBSTRING (*brl_reflection_TField_GetString_TObject_m)(struct brl_reflection_TField_obj*,BBOBJECT);
BBSTRING _brl_reflection_TField_GetString_TObject(struct brl_reflection_TField_obj*,BBOBJECT);
typedef BBINT (*brl_reflection_TField_Set_TObjectTObject_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBOBJECT);
BBINT _brl_reflection_TField_Set_TObjectTObject(struct brl_reflection_TField_obj*,BBOBJECT,BBOBJECT);
typedef BBINT (*brl_reflection_TField_Set_TObjectb_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBBYTE);
BBINT _brl_reflection_TField_Set_TObjectb(struct brl_reflection_TField_obj*,BBOBJECT,BBBYTE);
typedef BBINT (*brl_reflection_TField_Set_TObjects_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBSHORT);
BBINT _brl_reflection_TField_Set_TObjects(struct brl_reflection_TField_obj*,BBOBJECT,BBSHORT);
typedef BBINT (*brl_reflection_TField_Set_TObjecti_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBINT);
BBINT _brl_reflection_TField_Set_TObjecti(struct brl_reflection_TField_obj*,BBOBJECT,BBINT);
typedef BBINT (*brl_reflection_TField_Set_TObjectu_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBUINT);
BBINT _brl_reflection_TField_Set_TObjectu(struct brl_reflection_TField_obj*,BBOBJECT,BBUINT);
typedef BBINT (*brl_reflection_TField_Set_TObjectl_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBLONG);
BBINT _brl_reflection_TField_Set_TObjectl(struct brl_reflection_TField_obj*,BBOBJECT,BBLONG);
typedef BBINT (*brl_reflection_TField_Set_TObjecty_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBULONG);
BBINT _brl_reflection_TField_Set_TObjecty(struct brl_reflection_TField_obj*,BBOBJECT,BBULONG);
typedef BBINT (*brl_reflection_TField_Set_TObjectz_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBSIZET);
BBINT _brl_reflection_TField_Set_TObjectz(struct brl_reflection_TField_obj*,BBOBJECT,BBSIZET);
typedef BBINT (*brl_reflection_TField_Set_TObjectf_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBFLOAT);
BBINT _brl_reflection_TField_Set_TObjectf(struct brl_reflection_TField_obj*,BBOBJECT,BBFLOAT);
typedef BBINT (*brl_reflection_TField_Set_TObjectd_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBDOUBLE);
BBINT _brl_reflection_TField_Set_TObjectd(struct brl_reflection_TField_obj*,BBOBJECT,BBDOUBLE);
typedef BBINT (*brl_reflection_TField_SetObject_TObjectTObject_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBOBJECT);
BBINT _brl_reflection_TField_SetObject_TObjectTObject(struct brl_reflection_TField_obj*,BBOBJECT,BBOBJECT);
typedef BBINT (*brl_reflection_TField_SetByte_TObjectb_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBBYTE);
BBINT _brl_reflection_TField_SetByte_TObjectb(struct brl_reflection_TField_obj*,BBOBJECT,BBBYTE);
typedef BBINT (*brl_reflection_TField_SetShort_TObjects_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBSHORT);
BBINT _brl_reflection_TField_SetShort_TObjects(struct brl_reflection_TField_obj*,BBOBJECT,BBSHORT);
typedef BBINT (*brl_reflection_TField_SetInt_TObjecti_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBINT);
BBINT _brl_reflection_TField_SetInt_TObjecti(struct brl_reflection_TField_obj*,BBOBJECT,BBINT);
typedef BBINT (*brl_reflection_TField_SetUInt_TObjectu_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBUINT);
BBINT _brl_reflection_TField_SetUInt_TObjectu(struct brl_reflection_TField_obj*,BBOBJECT,BBUINT);
typedef BBINT (*brl_reflection_TField_SetLong_TObjectl_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBLONG);
BBINT _brl_reflection_TField_SetLong_TObjectl(struct brl_reflection_TField_obj*,BBOBJECT,BBLONG);
typedef BBINT (*brl_reflection_TField_SetULong_TObjecty_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBULONG);
BBINT _brl_reflection_TField_SetULong_TObjecty(struct brl_reflection_TField_obj*,BBOBJECT,BBULONG);
typedef BBINT (*brl_reflection_TField_SetSizet_TObjectz_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBSIZET);
BBINT _brl_reflection_TField_SetSizet_TObjectz(struct brl_reflection_TField_obj*,BBOBJECT,BBSIZET);
typedef BBINT (*brl_reflection_TField_SetFloat_TObjectf_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBFLOAT);
BBINT _brl_reflection_TField_SetFloat_TObjectf(struct brl_reflection_TField_obj*,BBOBJECT,BBFLOAT);
typedef BBINT (*brl_reflection_TField_SetDouble_TObjectd_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBDOUBLE);
BBINT _brl_reflection_TField_SetDouble_TObjectd(struct brl_reflection_TField_obj*,BBOBJECT,BBDOUBLE);
typedef BBINT (*brl_reflection_TField_SetString_TObjectS_m)(struct brl_reflection_TField_obj*,BBOBJECT,BBSTRING);
BBINT _brl_reflection_TField_SetString_TObjectS(struct brl_reflection_TField_obj*,BBOBJECT,BBSTRING);
struct BBClass_brl_reflection_TField {
	struct BBClass_brl_reflection_TMember*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TField_Init_STTTypeIdSi_m m_Init_STTTypeIdSi;
	brl_reflection_TField_Get_TObject_m m_Get_TObject;
	brl_reflection_TField_GetByte_TObject_m m_GetByte_TObject;
	brl_reflection_TField_GetShort_TObject_m m_GetShort_TObject;
	brl_reflection_TField_GetInt_TObject_m m_GetInt_TObject;
	brl_reflection_TField_GetUInt_TObject_m m_GetUInt_TObject;
	brl_reflection_TField_GetLong_TObject_m m_GetLong_TObject;
	brl_reflection_TField_GetULong_TObject_m m_GetULong_TObject;
	brl_reflection_TField_GetSizet_TObject_m m_GetSizet_TObject;
	brl_reflection_TField_GetFloat_TObject_m m_GetFloat_TObject;
	brl_reflection_TField_GetDouble_TObject_m m_GetDouble_TObject;
	brl_reflection_TField_GetString_TObject_m m_GetString_TObject;
	brl_reflection_TField_Set_TObjectTObject_m m_Set_TObjectTObject;
	brl_reflection_TField_Set_TObjectb_m m_Set_TObjectb;
	brl_reflection_TField_Set_TObjects_m m_Set_TObjects;
	brl_reflection_TField_Set_TObjecti_m m_Set_TObjecti;
	brl_reflection_TField_Set_TObjectu_m m_Set_TObjectu;
	brl_reflection_TField_Set_TObjectl_m m_Set_TObjectl;
	brl_reflection_TField_Set_TObjecty_m m_Set_TObjecty;
	brl_reflection_TField_Set_TObjectz_m m_Set_TObjectz;
	brl_reflection_TField_Set_TObjectf_m m_Set_TObjectf;
	brl_reflection_TField_Set_TObjectd_m m_Set_TObjectd;
	brl_reflection_TField_SetObject_TObjectTObject_m m_SetObject_TObjectTObject;
	brl_reflection_TField_SetByte_TObjectb_m m_SetByte_TObjectb;
	brl_reflection_TField_SetShort_TObjects_m m_SetShort_TObjects;
	brl_reflection_TField_SetInt_TObjecti_m m_SetInt_TObjecti;
	brl_reflection_TField_SetUInt_TObjectu_m m_SetUInt_TObjectu;
	brl_reflection_TField_SetLong_TObjectl_m m_SetLong_TObjectl;
	brl_reflection_TField_SetULong_TObjecty_m m_SetULong_TObjecty;
	brl_reflection_TField_SetSizet_TObjectz_m m_SetSizet_TObjectz;
	brl_reflection_TField_SetFloat_TObjectf_m m_SetFloat_TObjectf;
	brl_reflection_TField_SetDouble_TObjectd_m m_SetDouble_TObjectd;
	brl_reflection_TField_SetString_TObjectS_m m_SetString_TObjectS;
};

struct brl_reflection_TField_obj {
	struct BBClass_brl_reflection_TField* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
	BBINT _brl_reflection_tfield__index;
};
extern struct BBClass_brl_reflection_TField brl_reflection_TField;
void _brl_reflection_TGlobal_New(struct brl_reflection_TGlobal_obj* o);
typedef struct brl_reflection_TGlobal_obj* (*brl_reflection_TGlobal_Init_STTTypeIdSpb_m)(struct brl_reflection_TGlobal_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBBYTE*);
struct brl_reflection_TGlobal_obj* _brl_reflection_TGlobal_Init_STTTypeIdSpb(struct brl_reflection_TGlobal_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,BBBYTE*);
typedef BBOBJECT (*brl_reflection_TGlobal_Get_m)(struct brl_reflection_TGlobal_obj*);
BBOBJECT _brl_reflection_TGlobal_Get(struct brl_reflection_TGlobal_obj*);
typedef BBINT (*brl_reflection_TGlobal_GetInt_m)(struct brl_reflection_TGlobal_obj*);
BBINT _brl_reflection_TGlobal_GetInt(struct brl_reflection_TGlobal_obj*);
typedef BBLONG (*brl_reflection_TGlobal_GetLong_m)(struct brl_reflection_TGlobal_obj*);
BBLONG _brl_reflection_TGlobal_GetLong(struct brl_reflection_TGlobal_obj*);
typedef BBSIZET (*brl_reflection_TGlobal_GetSizet_m)(struct brl_reflection_TGlobal_obj*);
BBSIZET _brl_reflection_TGlobal_GetSizet(struct brl_reflection_TGlobal_obj*);
typedef BBFLOAT (*brl_reflection_TGlobal_GetFloat_m)(struct brl_reflection_TGlobal_obj*);
BBFLOAT _brl_reflection_TGlobal_GetFloat(struct brl_reflection_TGlobal_obj*);
typedef BBDOUBLE (*brl_reflection_TGlobal_GetDouble_m)(struct brl_reflection_TGlobal_obj*);
BBDOUBLE _brl_reflection_TGlobal_GetDouble(struct brl_reflection_TGlobal_obj*);
typedef BBSTRING (*brl_reflection_TGlobal_GetString_m)(struct brl_reflection_TGlobal_obj*);
BBSTRING _brl_reflection_TGlobal_GetString(struct brl_reflection_TGlobal_obj*);
typedef BBINT (*brl_reflection_TGlobal_Set_TObject_m)(struct brl_reflection_TGlobal_obj*,BBOBJECT);
BBINT _brl_reflection_TGlobal_Set_TObject(struct brl_reflection_TGlobal_obj*,BBOBJECT);
typedef BBINT (*brl_reflection_TGlobal_SetInt_i_m)(struct brl_reflection_TGlobal_obj*,BBINT);
BBINT _brl_reflection_TGlobal_SetInt_i(struct brl_reflection_TGlobal_obj*,BBINT);
typedef BBINT (*brl_reflection_TGlobal_SetLong_l_m)(struct brl_reflection_TGlobal_obj*,BBLONG);
BBINT _brl_reflection_TGlobal_SetLong_l(struct brl_reflection_TGlobal_obj*,BBLONG);
typedef BBINT (*brl_reflection_TGlobal_SetSizet_z_m)(struct brl_reflection_TGlobal_obj*,BBSIZET);
BBINT _brl_reflection_TGlobal_SetSizet_z(struct brl_reflection_TGlobal_obj*,BBSIZET);
typedef BBINT (*brl_reflection_TGlobal_SetFloat_f_m)(struct brl_reflection_TGlobal_obj*,BBFLOAT);
BBINT _brl_reflection_TGlobal_SetFloat_f(struct brl_reflection_TGlobal_obj*,BBFLOAT);
typedef BBINT (*brl_reflection_TGlobal_SetDouble_d_m)(struct brl_reflection_TGlobal_obj*,BBDOUBLE);
BBINT _brl_reflection_TGlobal_SetDouble_d(struct brl_reflection_TGlobal_obj*,BBDOUBLE);
typedef BBINT (*brl_reflection_TGlobal_SetString_S_m)(struct brl_reflection_TGlobal_obj*,BBSTRING);
BBINT _brl_reflection_TGlobal_SetString_S(struct brl_reflection_TGlobal_obj*,BBSTRING);
struct BBClass_brl_reflection_TGlobal {
	struct BBClass_brl_reflection_TMember*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TGlobal_Init_STTTypeIdSpb_m m_Init_STTTypeIdSpb;
	brl_reflection_TGlobal_Get_m m_Get;
	brl_reflection_TGlobal_GetInt_m m_GetInt;
	brl_reflection_TGlobal_GetLong_m m_GetLong;
	brl_reflection_TGlobal_GetSizet_m m_GetSizet;
	brl_reflection_TGlobal_GetFloat_m m_GetFloat;
	brl_reflection_TGlobal_GetDouble_m m_GetDouble;
	brl_reflection_TGlobal_GetString_m m_GetString;
	brl_reflection_TGlobal_Set_TObject_m m_Set_TObject;
	brl_reflection_TGlobal_SetInt_i_m m_SetInt_i;
	brl_reflection_TGlobal_SetLong_l_m m_SetLong_l;
	brl_reflection_TGlobal_SetSizet_z_m m_SetSizet_z;
	brl_reflection_TGlobal_SetFloat_f_m m_SetFloat_f;
	brl_reflection_TGlobal_SetDouble_d_m m_SetDouble_d;
	brl_reflection_TGlobal_SetString_S_m m_SetString_S;
};

struct brl_reflection_TGlobal_obj {
	struct BBClass_brl_reflection_TGlobal* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
	BBBYTE* _brl_reflection_tglobal__ref;
};
extern struct BBClass_brl_reflection_TGlobal brl_reflection_TGlobal;
void _brl_reflection_TFunction_New(struct brl_reflection_TFunction_obj* o);
typedef struct brl_reflection_TFunction_obj* (*brl_reflection_TFunction_Init_STTTypeIdSTTTypeIdpbaTTTypeId_m)(struct brl_reflection_TFunction_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBBYTE*,BBARRAY);
struct brl_reflection_TFunction_obj* _brl_reflection_TFunction_Init_STTTypeIdSTTTypeIdpbaTTTypeId(struct brl_reflection_TFunction_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBBYTE*,BBARRAY);
typedef BBARRAY (*brl_reflection_TFunction_ArgTypes_m)(struct brl_reflection_TFunction_obj*);
BBARRAY _brl_reflection_TFunction_ArgTypes(struct brl_reflection_TFunction_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TFunction_ReturnType_m)(struct brl_reflection_TFunction_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TFunction_ReturnType(struct brl_reflection_TFunction_obj*);
typedef BBBYTE* (*brl_reflection_TFunction_FunctionPtr_m)(struct brl_reflection_TFunction_obj*);
BBBYTE* _brl_reflection_TFunction_FunctionPtr(struct brl_reflection_TFunction_obj*);
typedef BBOBJECT (*brl_reflection_TFunction_Invoke_aTObject_m)(struct brl_reflection_TFunction_obj*,BBARRAY);
BBOBJECT _brl_reflection_TFunction_Invoke_aTObject(struct brl_reflection_TFunction_obj*,BBARRAY);
struct BBClass_brl_reflection_TFunction {
	struct BBClass_brl_reflection_TMember*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TFunction_Init_STTTypeIdSTTTypeIdpbaTTTypeId_m m_Init_STTTypeIdSTTTypeIdpbaTTTypeId;
	brl_reflection_TFunction_ArgTypes_m m_ArgTypes;
	brl_reflection_TFunction_ReturnType_m m_ReturnType;
	brl_reflection_TFunction_FunctionPtr_m m_FunctionPtr;
	brl_reflection_TFunction_Invoke_aTObject_m m_Invoke_aTObject;
};

struct brl_reflection_TFunction_obj {
	struct BBClass_brl_reflection_TFunction* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tfunction__selftypeid;
	BBBYTE* _brl_reflection_tfunction__ref;
	BBARRAY _brl_reflection_tfunction__argtypes;
};
extern struct BBClass_brl_reflection_TFunction brl_reflection_TFunction;
void _brl_reflection_TMethod_New(struct brl_reflection_TMethod_obj* o);
typedef struct brl_reflection_TMethod_obj* (*brl_reflection_TMethod_Init_STTTypeIdSTTTypeIdpbaTTTypeId_m)(struct brl_reflection_TMethod_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBBYTE*,BBARRAY);
struct brl_reflection_TMethod_obj* _brl_reflection_TMethod_Init_STTTypeIdSTTTypeIdpbaTTTypeId(struct brl_reflection_TMethod_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBSTRING,struct brl_reflection_TTypeId_obj*,BBBYTE*,BBARRAY);
typedef BBARRAY (*brl_reflection_TMethod_ArgTypes_m)(struct brl_reflection_TMethod_obj*);
BBARRAY _brl_reflection_TMethod_ArgTypes(struct brl_reflection_TMethod_obj*);
typedef struct brl_reflection_TTypeId_obj* (*brl_reflection_TMethod_ReturnType_m)(struct brl_reflection_TMethod_obj*);
struct brl_reflection_TTypeId_obj* _brl_reflection_TMethod_ReturnType(struct brl_reflection_TMethod_obj*);
typedef BBOBJECT (*brl_reflection_TMethod_Invoke_TObjectaTObject_m)(struct brl_reflection_TMethod_obj*,BBOBJECT,BBARRAY);
BBOBJECT _brl_reflection_TMethod_Invoke_TObjectaTObject(struct brl_reflection_TMethod_obj*,BBOBJECT,BBARRAY);
struct BBClass_brl_reflection_TMethod {
	struct BBClass_brl_reflection_TMember*  super;
	void      (*free)( BBObject *o );
	BBDebugScope* debug_scope;
	unsigned int instance_size;
	void      (*ctor)( BBOBJECT o );
	void      (*dtor)( BBOBJECT o );
	BBSTRING  (*ToString)( BBOBJECT x );
	int       (*Compare)( BBOBJECT x,BBOBJECT y );
	BBOBJECT  (*SendMessage)( BBOBJECT o,BBOBJECT m,BBOBJECT s );
	BBINTERFACETABLE itable;
	void*     extra;
	unsigned int obj_size;
	unsigned int instance_count;
	unsigned int fields_offset;
	brl_reflection_TMember_Name_m m_Name;
	brl_reflection_TMember_NameLower_m m_NameLower;
	brl_reflection_TMember_TypeId_m m_TypeId;
	brl_reflection_TMember_MetaData_S_m m_MetaData_S;
	brl_reflection_TMember_HasMetaData_S_m m_HasMetaData_S;
	brl_reflection_TMember_InitMeta_S_m m_InitMeta_S;
	brl_reflection_TMethod_Init_STTTypeIdSTTTypeIdpbaTTTypeId_m m_Init_STTTypeIdSTTTypeIdpbaTTTypeId;
	brl_reflection_TMethod_ArgTypes_m m_ArgTypes;
	brl_reflection_TMethod_ReturnType_m m_ReturnType;
	brl_reflection_TMethod_Invoke_TObjectaTObject_m m_Invoke_TObjectaTObject;
};

struct brl_reflection_TMethod_obj {
	struct BBClass_brl_reflection_TMethod* clas;
	BBSTRING _brl_reflection_tmember__name;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmember__typeid;
	BBSTRING _brl_reflection_tmember__meta;
	BBSTRING _brl_reflection_tmember__namelower;
	struct brl_map_stringmap_TStringMap_obj* _brl_reflection_tmember__metamap;
	struct brl_reflection_TTypeId_obj* _brl_reflection_tmethod__selftypeid;
	BBBYTE* _brl_reflection_tmethod__ref;
	BBARRAY _brl_reflection_tmethod__argtypes;
};
extern struct BBClass_brl_reflection_TMethod brl_reflection_TMethod;
extern BBINT bbRefArrayLength(BBOBJECT bbt__array,BBINT bbt_dim);
extern BBSTRING bbRefArrayTypeTag(BBOBJECT bbt__array);
extern BBINT bbRefArrayDimensions(BBOBJECT bbt__array);
extern BBOBJECT bbRefArrayCreate(BBBYTE* bbt_typeTag,BBARRAY bbt_dims);
extern BBBYTE* bbRefFieldPtr(BBOBJECT bbt_obj,BBINT bbt_index);
extern BBBYTE* bbRefMethodPtr(BBOBJECT bbt_obj,BBINT bbt_index);
extern BBBYTE* bbRefArrayElementPtr(BBINT bbt_sz,BBOBJECT bbt__array,BBINT bbt_index);
extern BBOBJECT bbRefGetObject(BBBYTE* bbt_p);
extern BBINT bbRefPushObject(BBBYTE* bbt_p,BBOBJECT bbt_obj);
extern BBINT bbRefInitObject(BBBYTE* bbt_p,BBOBJECT bbt_obj);
extern BBINT bbRefAssignObject(BBBYTE* bbt_p,BBOBJECT bbt_obj);
extern BBBYTE* bbRefGetObjectClass(BBOBJECT bbt_obj);
extern BBBYTE* bbRefGetSuperClass(BBBYTE* bbt_class);
extern BBSTRING bbStringFromRef(BBBYTE* bbt_ref);
extern BBOBJECT bbRefArrayNull();
extern BBBYTE* bbInterfaceName(BBBYTE* bbt_ifc);
extern BBBYTE* bbInterfaceClass(BBBYTE* bbt_ifc);
extern BBINT bbObjectImplementsInterfaces(BBBYTE* bbt_class);
extern BBINT bbObjectImplementedCount(BBBYTE* bbt_class);
extern BBBYTE* bbObjectImplementedInterface(BBBYTE* bbt_class,BBINT bbt_index);
extern BBBYTE* bbRefClassSuper(BBBYTE* bbt_clas);
extern BBBYTE* bbRefClassDebugScope(BBBYTE* bbt_clas);
extern BBBYTE* bbRefClassDebugDecl(BBBYTE* bbt_clas);
extern BBBYTE* bbRefClassDebugScopeName(BBBYTE* bbt_class);
extern BBINT bbDebugDeclKind(BBBYTE* bbt_decl);
extern BBBYTE* bbDebugDeclName(BBBYTE* bbt_decl);
extern BBBYTE* bbDebugDeclType(BBBYTE* bbt_decl);
extern BBSTRING bbDebugDeclConstValue(BBBYTE* bbt_decl);
extern BBINT bbDebugDeclFieldOffset(BBBYTE* bbt_decl);
extern BBBYTE* bbDebugDeclVarAddress(BBBYTE* bbt_decl);
extern BBBYTE* bbDebugDeclNext(BBBYTE* bbt_decl);
BBOBJECT brl_reflection__Get(BBBYTE* bbt_p,struct brl_reflection_TTypeId_obj* bbt_typeId);
BBBYTE* brl_reflection__Push(BBBYTE* bbt_sp,struct brl_reflection_TTypeId_obj* bbt_typeId,BBOBJECT bbt_value);
BBINT brl_reflection__Assign(BBBYTE* bbt_p,struct brl_reflection_TTypeId_obj* bbt_typeId,BBOBJECT bbt_value);
BBOBJECT brl_reflection__CallFunction(BBBYTE* bbt_p,struct brl_reflection_TTypeId_obj* bbt_typeId,BBARRAY bbt_args,BBARRAY bbt_argTypes);
BBOBJECT brl_reflection__CallMethod(BBBYTE* bbt_p,struct brl_reflection_TTypeId_obj* bbt_typeId,BBOBJECT bbt_obj,BBARRAY bbt_args,BBARRAY bbt_argTypes);
BBSTRING brl_reflection_TypeTagForId(struct brl_reflection_TTypeId_obj* bbt_id);
struct brl_map_stringmap_TStringMap_obj* brl_reflection_ExtractMetaMap(BBSTRING bbt_meta);
struct brl_reflection_TTypeId_obj* brl_reflection_TypeIdForTag(BBSTRING bbt_ty);

#endif
